In [1]:
import pandas as pd

In [94]:
aisd2 = pd.read_csv("AiSD2.csv")

In [95]:
aisd2

,Imię,Nazwisko,Z1(4+1),Z2(4+1),Z3(4+1),Z4(4+1),Z5(2+2),Z6(4+1),Z7(4+1),Z8(4+1),Z9(4+1),Z10(4+1),Z11(4+1),Z12(4+1),Z13(5),Z14(4+1),Z15(5)
0,Anna,Nowak,2.5+1.0,4.0+1.0,2.0+0.0,1.0+2.0,1.5+2.0,2.0+0.0,0.0+NB,1.5+1.0,3.5+0.5,2.0+0.0,0.5+1.0,ZW+ZW,4.0+0.0,4.0+1.0,NA
1,Rafał,Kowalski,3.0+0.0,2.0+0.5,2.0+1.0,1.5+1.5,2.0+1.0,1.0+0.5,0.0+NB,3.0+1.0,3.5+1.0,0.0+NB,1.0+1.0,NS.(3.0)+NS.(1.0),4.0+0.0,4.0+1.0,NA
2,Pavlo,Wiśniewski,2.5+0.5,US+1.0,2.5+1.0,1.5+1.5,2.0+1.5,3.5+0.0,1.0+1.0,3.0+1.0,3.5+1.0,ZW+ZW,1.0+0.5,3.5+1.0,4.0+1.0,4.0+1.0,NA
3,Aleksy,Dąbrowski,0.5+1.0,1.0+1.0,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA
4,Jarosław,Lewandowski,2.0+0.0,3.0+1.0,1.0+0.0,1.5+1.5,0.5+0.0,1.25+0.0,0.0+NB,2.5+0.0,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA
5,Bartłomiej,Wójcik,2.0+1.0,2.0+1.0,2.5+0.5,1.5+1.5,0.5+1.0,1.75+0.5,0.0+1.0,1.5+1.0,4.0+1.0,ZW+ZW,0.5+1.0,3.0+0.0,4.0+1.0,3.5+0.0,NA
6,Łukasz,Kamiński,4.0+1.0,2.0+1.0,3.5+1.0,1.5+0.5,1.5+0.5,US+1.0,0.5+1.0,2.0+1.0,3.5+1.0,2.0+0.0,0.5+0.5,3.0+1.0,2.0+1.0,4.0+1.0,NA
7,Oskar,Kowalczyk,4.0+0.5,4.0+1.0,2.0+1.0,4.0+2.0,2.0+1.0,1.5+0.0,1.0+1.0,4.0+1.0,4.0+1.0,1.0+0.5,0.0+NB,3.5+1.0,4.0+1.0,3.0+0.0,NA
8,Joanna,Zielińska,2.5+0.0,US+US,0.5+0.0,1.0+0.0,0.5+1.0,1.0+0.0,0.5+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA
9,Oktawia,Szymański,2.5+1.0,0.0+0.0,1.0+0.5,0.0+1.5,0.5+0.5,NB+NB,0.0+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA
10,Patryk,Woźniak,2.0+1.0,4.0+1.0,2.5+1.0,3.0+2.0,1.0+0.5,1.0+0.5,1.0+0.5,2.0+1.0,4.0+1.0,2.0+0.5,4.0+1.0,4.0+1.0,2.0+0.0,4.0+1.0,NA

In [96]:
from unidecode import unidecode

In [110]:
aisd2.columns = aisd2.columns.str.strip()

In [111]:
aisd2['Nazwisko'] = aisd2['Nazwisko'].str.strip()

In [113]:
aisd2['Imię'] = aisd2['Imię'].str.strip()

In [114]:
for column in aisd2.columns:
    aisd2[column] = aisd2[column].str.strip()

In [115]:
aisd2.columns

Index(['Imię', 'Nazwisko', 'Z1(4+1)', 'Z2(4+1)', 'Z3(4+1)', 'Z4(4+1)',
       'Z5(2+2)', 'Z6(4+1)', 'Z7(4+1)', 'Z8(4+1)', 'Z9(4+1)', 'Z10(4+1)',
       'Z11(4+1)', 'Z12(4+1)', 'Z13(5)', 'Z14(4+1)', 'Z15(5)', 'email'],
      dtype='object')

In [116]:
aisd2['email'] = aisd2.Nazwisko.str.lower().apply(unidecode) + aisd2.Imię.str.lower().str[0].apply(unidecode) + '@student.mini.pw.edu.pl'

In [117]:
aisd2

,Imię,Nazwisko,Z1(4+1),Z2(4+1),Z3(4+1),Z4(4+1),Z5(2+2),Z6(4+1),Z7(4+1),Z8(4+1),Z9(4+1),Z10(4+1),Z11(4+1),Z12(4+1),Z13(5),Z14(4+1),Z15(5),email
0,Anna,Nowak,2.5+1.0,4.0+1.0,2.0+0.0,1.0+2.0,1.5+2.0,2.0+0.0,0.0+NB,1.5+1.0,3.5+0.5,2.0+0.0,0.5+1.0,ZW+ZW,4.0+0.0,4.0+1.0,NA,nowaka@student.mini.pw.edu.pl
1,Rafał,Kowalski,3.0+0.0,2.0+0.5,2.0+1.0,1.5+1.5,2.0+1.0,1.0+0.5,0.0+NB,3.0+1.0,3.5+1.0,0.0+NB,1.0+1.0,NS.(3.0)+NS.(1.0),4.0+0.0,4.0+1.0,NA,kowalskir@student.mini.pw.edu.pl
2,Pavlo,Wiśniewski,2.5+0.5,US+1.0,2.5+1.0,1.5+1.5,2.0+1.5,3.5+0.0,1.0+1.0,3.0+1.0,3.5+1.0,ZW+ZW,1.0+0.5,3.5+1.0,4.0+1.0,4.0+1.0,NA,wisniewskip@student.mini.pw.edu.pl
3,Aleksy,Dąbrowski,0.5+1.0,1.0+1.0,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA,dabrowskia@student.mini.pw.edu.pl
4,Jarosław,Lewandowski,2.0+0.0,3.0+1.0,1.0+0.0,1.5+1.5,0.5+0.0,1.25+0.0,0.0+NB,2.5+0.0,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA,lewandowskij@student.mini.pw.edu.pl
5,Bartłomiej,Wójcik,2.0+1.0,2.0+1.0,2.5+0.5,1.5+1.5,0.5+1.0,1.75+0.5,0.0+1.0,1.5+1.0,4.0+1.0,ZW+ZW,0.5+1.0,3.0+0.0,4.0+1.0,3.5+0.0,NA,wojcikb@student.mini.pw.edu.pl
6,Łukasz,Kamiński,4.0+1.0,2.0+1.0,3.5+1.0,1.5+0.5,1.5+0.5,US+1.0,0.5+1.0,2.0+1.0,3.5+1.0,2.0+0.0,0.5+0.5,3.0+1.0,2.0+1.0,4.0+1.0,NA,kaminskil@student.mini.pw.edu.pl
7,Oskar,Kowalczyk,4.0+0.5,4.0+1.0,2.0+1.0,4.0+2.0,2.0+1.0,1.5+0.0,1.0+1.0,4.0+1.0,4.0+1.0,1.0+0.5,0.0+NB,3.5+1.0,4.0+1.0,3.0+0.0,NA,kowalczyko@student.mini.pw.edu.pl
8,Joanna,Zielińska,2.5+0.0,US+US,0.5+0.0,1.0+0.0,0.5+1.0,1.0+0.0,0.5+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA,zielinskaj@student.mini.pw.edu.pl
9,Oktawia,Szymański,2.5+1.0,0.0+0.0,1.0+0.5,0.0+1.5,0.5+0.5,NB+NB,0.0+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA,szymanskio@student.mini.pw.edu.pl
10,Patryk,Woźniak,2.0+1.0,4.0+1.0,2.5+1.0,3.0+2.0,1.0+0.5,1.0+0.5,1.0+0.5,2.0+1.0,4.0+1.0,2.0+0.5,4.0+1.0,4.0+1.0,2.0+0.0,4.0+1.0,NA,wozniakp@student.mini.pw.edu.pl

In [119]:
aisd2['email'].str.cat(sep=', ')

'nowaka@student.mini.pw.edu.pl, kowalskir@student.mini.pw.edu.pl, wisniewskip@student.mini.pw.edu.pl, dabrowskia@student.mini.pw.edu.pl, lewandowskij@student.mini.pw.edu.pl, wojcikb@student.mini.pw.edu.pl, kaminskil@student.mini.pw.edu.pl, kowalczyko@student.mini.pw.edu.pl, zielinskaj@student.mini.pw.edu.pl, szymanskio@student.mini.pw.edu.pl, wozniakp@student.mini.pw.edu.pl'

In [123]:
import re

In [165]:
match = re.search(r'(\w+)\((\d+)\+(\d+)\)', 'Z5(4+1)')

In [166]:
match.group()

'Z5(4+1)'

In [167]:
match.group(0)

'Z5(4+1)'

In [140]:
match.group(1)

'Z5'

In [141]:
match.group(2)

'4'

In [142]:
match.group(3)

'1'

In [150]:
list(range(2, 14)) + [15]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15]

In [152]:
aisd2.columns[list(range(2, 14)) + [15]]

Index(['Z1(4+1)', 'Z2(4+1)', 'Z3(4+1)', 'Z4(4+1)', 'Z5(2+2)', 'Z6(4+1)',
       'Z7(4+1)', 'Z8(4+1)', 'Z9(4+1)', 'Z10(4+1)', 'Z11(4+1)', 'Z12(4+1)',
       'Z14(4+1)'],
      dtype='object')

In [209]:
def match_name(str):
    return re.search(r'(\w+)\((\d+)\+(\d+)\)', str)

def col1name(match):
    return 'L' + '(' + match.group(2) + ')'

def col2name(match):
    return 'T' + '(' + match.group(3) + ')'

def match_val(str):
    raturn re.search(r'([\d.]+)\+([\d.]+)', str)
    
def col1val(match):
    return match.group(1)

def col2val(match):
    return match.group(2)

In [213]:
aisd2[col1name(match_name(aisd2.columns[2]))] = [col1va
aisd2[col2name(match_name(aisd2.columns[2]))] = 1

In [230]:
aisd2

,Imię,Nazwisko,Z1(4+1),Z2(4+1),Z3(4+1),Z4(4+1),Z5(2+2),Z6(4+1),Z7(4+1),Z8(4+1),Z9(4+1),Z10(4+1),Z11(4+1),Z12(4+1),Z13(5),Z14(4+1),Z15(5),email
0,Anna,Nowak,2.5+1.0,4.0+1.0,2.0+0.0,1.0+2.0,1.5+2.0,2.0+0.0,0.0+NB,1.5+1.0,3.5+0.5,2.0+0.0,0.5+1.0,ZW+ZW,4.0+0.0,4.0+1.0,NA,nowaka@student.mini.pw.edu.pl
1,Rafał,Kowalski,3.0+0.0,2.0+0.5,2.0+1.0,1.5+1.5,2.0+1.0,1.0+0.5,0.0+NB,3.0+1.0,3.5+1.0,0.0+NB,1.0+1.0,NS.(3.0)+NS.(1.0),4.0+0.0,4.0+1.0,NA,kowalskir@student.mini.pw.edu.pl
2,Pavlo,Wiśniewski,2.5+0.5,US+1.0,2.5+1.0,1.5+1.5,2.0+1.5,3.5+0.0,1.0+1.0,3.0+1.0,3.5+1.0,ZW+ZW,1.0+0.5,3.5+1.0,4.0+1.0,4.0+1.0,NA,wisniewskip@student.mini.pw.edu.pl
3,Aleksy,Dąbrowski,0.5+1.0,1.0+1.0,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA,dabrowskia@student.mini.pw.edu.pl
4,Jarosław,Lewandowski,2.0+0.0,3.0+1.0,1.0+0.0,1.5+1.5,0.5+0.0,1.25+0.0,0.0+NB,2.5+0.0,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA,lewandowskij@student.mini.pw.edu.pl
5,Bartłomiej,Wójcik,2.0+1.0,2.0+1.0,2.5+0.5,1.5+1.5,0.5+1.0,1.75+0.5,0.0+1.0,1.5+1.0,4.0+1.0,ZW+ZW,0.5+1.0,3.0+0.0,4.0+1.0,3.5+0.0,NA,wojcikb@student.mini.pw.edu.pl
6,Łukasz,Kamiński,4.0+1.0,2.0+1.0,3.5+1.0,1.5+0.5,1.5+0.5,US+1.0,0.5+1.0,2.0+1.0,3.5+1.0,2.0+0.0,0.5+0.5,3.0+1.0,2.0+1.0,4.0+1.0,NA,kaminskil@student.mini.pw.edu.pl
7,Oskar,Kowalczyk,4.0+0.5,4.0+1.0,2.0+1.0,4.0+2.0,2.0+1.0,1.5+0.0,1.0+1.0,4.0+1.0,4.0+1.0,1.0+0.5,0.0+NB,3.5+1.0,4.0+1.0,3.0+0.0,NA,kowalczyko@student.mini.pw.edu.pl
8,Joanna,Zielińska,2.5+0.0,US+US,0.5+0.0,1.0+0.0,0.5+1.0,1.0+0.0,0.5+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA,zielinskaj@student.mini.pw.edu.pl
9,Oktawia,Szymański,2.5+1.0,0.0+0.0,1.0+0.5,0.0+1.5,0.5+0.5,NB+NB,0.0+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NA,szymanskio@student.mini.pw.edu.pl
10,Patryk,Woźniak,2.0+1.0,4.0+1.0,2.5+1.0,3.0+2.0,1.0+0.5,1.0+0.5,1.0+0.5,2.0+1.0,4.0+1.0,2.0+0.5,4.0+1.0,4.0+1.0,2.0+0.0,4.0+1.0,NA,wozniakp@student.mini.pw.edu.pl

In [216]:
match = re.search(r'([\d.]+)\+([\d.]+)', '2.5+1.0')

In [217]:
match.group(0)

'2.5+1.0'

In [218]:
match.group(1)

'2.5'

In [219]:
match.group(2)

'1.0'

In [231]:
for columnIndex in range(2, 17):
    #print(columnIndex, ramka.columns[columnIndex])
    wyrazenie = re.findall(r"Z(\d{1,2})\((\d)\+(\d)\)", aisd2.columns[columnIndex])
    if len(wyrazenie) == 1:
        numerZadania = wyrazenie[0][0]
        maksLab = wyrazenie[0][1]
        maksDom = wyrazenie[0][2]
        #ramka["L"+numerZadania+"("+maksLab+")"] = ramka.iloc[:,columnIndex].str.split("+").apply(lambda x: 0 if x == "NA" or x == "US" else float(x[0]))
        #ramka["T"+numerZadania+"("+maksDom+")"] = ramka.iloc[:,columnIndex].str.split("+").apply(lambda x: 0 if x == "NA" or x == "US" else float(x[1]))
        aisd2["L"+numerZadania+"("+maksLab+")"] = aisd2.iloc[:,columnIndex].str.split("+").apply(lambda x: x[0])
        aisd2["T"+numerZadania+"("+maksDom+")"] = aisd2.iloc[:,columnIndex].str.split("+").apply(lambda x: x[1])
    else:
        wyrazenie = re.findall(r"Z(\d{1,2})\((\d)\)", aisd2.columns[columnIndex])
        numerZadania = wyrazenie[0][0]
        maksLab = wyrazenie[0][1]
        aisd2["L"+numerZadania+"("+maksLab+")"] = aisd2.iloc[:,columnIndex].str.split("+").apply(lambda x: x[0])
    
aisd2 = aisd2.drop(aisd2.columns[range(2,17)], axis=1)

In [232]:
aisd2

,Imię,Nazwisko,email,L1(4),T1(1),L2(4),T2(1),L3(4),T3(1),L4(4),...,L10(4),T10(1),L11(4),T11(1),L12(4),T12(1),L13(5),L14(4),T14(1),L15(5)
0,Anna,Nowak,nowaka@student.mini.pw.edu.pl,2.5,1.0,4.0,1.0,2.0,0.0,1.0,...,2.0,0.0,0.5,1.0,ZW,ZW,4.0,4.0,1.0,NA
1,Rafał,Kowalski,kowalskir@student.mini.pw.edu.pl,3.0,0.0,2.0,0.5,2.0,1.0,1.5,...,0.0,NB,1.0,1.0,NS.(3.0),NS.(1.0),4.0,4.0,1.0,NA
2,Pavlo,Wiśniewski,wisniewskip@student.mini.pw.edu.pl,2.5,0.5,US,1.0,2.5,1.0,1.5,...,ZW,ZW,1.0,0.5,3.5,1.0,4.0,4.0,1.0,NA
3,Aleksy,Dąbrowski,dabrowskia@student.mini.pw.edu.pl,0.5,1.0,1.0,1.0,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,Jarosław,Lewandowski,lewandowskij@student.mini.pw.edu.pl,2.0,0.0,3.0,1.0,1.0,0.0,1.5,...,NB,NB,NB,NB,NB,NB,NB,NB,NB,NA
5,Bartłomiej,Wójcik,wojcikb@student.mini.pw.edu.pl,2.0,1.0,2.0,1.0,2.5,0.5,1.5,...,ZW,ZW,0.5,1.0,3.0,0.0,4.0,3.5,0.0,NA
6,Łukasz,Kamiński,kaminskil@student.mini.pw.edu.pl,4.0,1.0,2.0,1.0,3.5,1.0,1.5,...,2.0,0.0,0.5,0.5,3.0,1.0,2.0,4.0,1.0,NA
7,Oskar,Kowalczyk,kowalczyko@student.mini.pw.edu.pl,4.0,0.5,4.0,1.0,2.0,1.0,4.0,...,1.0,0.5,0.0,NB,3.5,1.0,4.0,3.0,0.0,NA
8,Joanna,Zielińska,zielinskaj@student.mini.pw.edu.pl,2.5,0.0,US,US,0.5,0.0,1.0,...,NB,NB,NB,NB,NB,NB,NB,NB,NB,NA
9,Oktawia,Szymański,szymanskio@student.mini.pw.edu.pl,2.5,1.0,0.0,0.0,1.0,0.5,0.0,...,NB,NB,NB,NB,NB,NB,NB,NB,NB,NA
10,Patryk,Woźniak,wozniakp@student.mini.pw.edu.pl,2.0,1.0,4.0,1.0,2.5,1.0,3.0,...,2.0,0.5,4.0,1.0,4.0,1.0,2.0,4.0,1.0,NA

In [240]:
aisd2 = aisd2.replace(['NA', 'NB', 'NS'], 0)

In [245]:
aisd2 = aisd2.replace(r'NS.*', 0, regex=True)

In [250]:
aisd2

,Imię,Nazwisko,email,L1(4),T1(1),L2(4),T2(1),L3(4),T3(1),L4(4),...,L10(4),T10(1),L11(4),T11(1),L12(4),T12(1),L13(5),L14(4),T14(1),L15(5)
0,Anna,Nowak,nowaka@student.mini.pw.edu.pl,2.5,1.0,4.0,1.0,2.0,0.0,1.0,...,2.0,0.0,0.5,1.0,ZW,ZW,4.0,4.0,1.0,0
1,Rafał,Kowalski,kowalskir@student.mini.pw.edu.pl,3.0,0.0,2.0,0.5,2.0,1.0,1.5,...,0.0,0,1.0,1.0,0,0,4.0,4.0,1.0,0
2,Pavlo,Wiśniewski,wisniewskip@student.mini.pw.edu.pl,2.5,0.5,US,1.0,2.5,1.0,1.5,...,ZW,ZW,1.0,0.5,3.5,1.0,4.0,4.0,1.0,0
3,Aleksy,Dąbrowski,dabrowskia@student.mini.pw.edu.pl,0.5,1.0,1.0,1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Jarosław,Lewandowski,lewandowskij@student.mini.pw.edu.pl,2.0,0.0,3.0,1.0,1.0,0.0,1.5,...,0,0,0,0,0,0,0,0,0,0
5,Bartłomiej,Wójcik,wojcikb@student.mini.pw.edu.pl,2.0,1.0,2.0,1.0,2.5,0.5,1.5,...,ZW,ZW,0.5,1.0,3.0,0.0,4.0,3.5,0.0,0
6,Łukasz,Kamiński,kaminskil@student.mini.pw.edu.pl,4.0,1.0,2.0,1.0,3.5,1.0,1.5,...,2.0,0.0,0.5,0.5,3.0,1.0,2.0,4.0,1.0,0
7,Oskar,Kowalczyk,kowalczyko@student.mini.pw.edu.pl,4.0,0.5,4.0,1.0,2.0,1.0,4.0,...,1.0,0.5,0.0,0,3.5,1.0,4.0,3.0,0.0,0
8,Joanna,Zielińska,zielinskaj@student.mini.pw.edu.pl,2.5,0.0,US,US,0.5,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
9,Oktawia,Szymański,szymanskio@student.mini.pw.edu.pl,2.5,1.0,0.0,0.0,1.0,0.5,0.0,...,0,0,0,0,0,0,0,0,0,0
10,Patryk,Woźniak,wozniakp@student.mini.pw.edu.pl,2.0,1.0,4.0,1.0,2.5,1.0,3.0,...,2.0,0.5,4.0,1.0,4.0,1.0,2.0,4.0,1.0,0

In [254]:
for columnIndex in range(3, 31):
    aisd2.iloc[:,columnIndex] = aisd2.iloc[:,columnIndex].apply(lambda x: "0" if x == "NA" or x == "NB" or "NS" in x else x)
aisd2

TypeError: argument of type 'int' is not iterable

In [255]:
import numpy as np

In [256]:
for columnIndex in range(3, 31):
    for rowIndex in range(aisd2.shape[0]):
        if aisd2.iloc[rowIndex, columnIndex] in ["ZW", "US"] :
            aisd2.iloc[rowIndex, columnIndex] = np.nan
            
for columnIndex in range(3, 31):
    aisd2.iloc[:, columnIndex] = aisd2.iloc[:, columnIndex].astype(float)
aisd2

ramkaKopia = aisd2.copy()

for columnIndex in range(3, 31):
    for rowIndex in range(ramkaKopia.shape[0]):
        if np.isnan(ramkaKopia.iloc[rowIndex, columnIndex]):
            aisd2.iloc[rowIndex, columnIndex] = np.mean(np.r_[ramkaKopia.iloc[:, columnIndex].mean(), ramkaKopia.iloc[rowIndex, 3:31].mean()])       
aisd2

,Imię,Nazwisko,email,L1(4),T1(1),L2(4),T2(1),L3(4),T3(1),L4(4),...,L10(4),T10(1),L11(4),T11(1),L12(4),T12(1),L13(5),L14(4),T14(1),L15(5)
0,Anna,Nowak,nowaka@student.mini.pw.edu.pl,2.5,1.0,4.000000,1.000000,2.0,0.0,1.0,...,2.000000,0.000000,0.5,1.0,1.580769,0.930769,4.0,4.0,1.0,0.0
1,Rafał,Kowalski,kowalskir@student.mini.pw.edu.pl,3.0,0.0,2.000000,0.500000,2.0,1.0,1.5,...,0.000000,0.000000,1.0,1.0,0.000000,0.000000,4.0,4.0,1.0,0.0
2,Pavlo,Wiśniewski,wisniewskip@student.mini.pw.edu.pl,2.5,0.5,2.082222,1.000000,2.5,1.0,1.5,...,1.248889,0.915556,1.0,0.5,3.500000,1.000000,4.0,4.0,1.0,0.0
3,Aleksy,Dąbrowski,dabrowskia@student.mini.pw.edu.pl,0.5,1.0,1.000000,1.000000,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
4,Jarosław,Lewandowski,lewandowskij@student.mini.pw.edu.pl,2.0,0.0,3.000000,1.000000,1.0,0.0,1.5,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
5,Bartłomiej,Wójcik,wojcikb@student.mini.pw.edu.pl,2.0,1.0,2.000000,1.000000,2.5,0.5,1.5,...,1.086004,0.752671,0.5,1.0,3.000000,0.000000,4.0,3.5,0.0,0.0
6,Łukasz,Kamiński,kaminskil@student.mini.pw.edu.pl,4.0,1.0,2.000000,1.000000,3.5,1.0,1.5,...,2.000000,0.000000,0.5,0.5,3.000000,1.000000,2.0,4.0,1.0,0.0
7,Oskar,Kowalczyk,kowalczyko@student.mini.pw.edu.pl,4.0,0.5,4.000000,1.000000,2.0,1.0,4.0,...,1.000000,0.500000,0.0,0.0,3.500000,1.000000,4.0,3.0,0.0,0.0
8,Joanna,Zielińska,zielinskaj@student.mini.pw.edu.pl,2.5,0.0,1.356838,0.559615,0.5,0.0,1.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
9,Oktawia,Szymański,szymanskio@student.mini.pw.edu.pl,2.5,1.0,0.000000,0.000000,1.0,0.5,0.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
10,Patryk,Woźniak,wozniakp@student.mini.pw.edu.pl,2.0,1.0,4.000000,1.000000,2.5,1.0,3.0,...,2.000000,0.500000,4.0,1.0,4.000000,1.000000,2.0,4.0,1.0,0.0

In [279]:
a = aisd2.columns[3:].map(lambda x : re.search(r'\(\d\)', x).group())

In [282]:
a

array(['(4)', '(1)', '(4)', '(1)', '(4)', '(1)', '(4)', '(1)', '(2)',
       '(2)', '(4)', '(1)', '(4)', '(1)', '(4)', '(1)', '(4)', '(1)',
       '(4)', '(1)', '(4)', '(1)', '(4)', '(1)', '(5)', '(4)', '(1)', '(5)'], dtype=object)

In [ ]:
maksPunkty = 0
for columnIndex in range(3, 31):
    wyrazenie = re.findall(r"[LT]\d{1,2}\((\d)\)", ramka.columns[columnIndex])
    punkty = float(wyrazenie[0])
    #print(punkty)
    maksPunkty += punkty
maksPunkty

procenty = np.empty(ramkaKopia.shape[0])
for rowIndex in range(ramkaKopia.shape[0]):
    procenty[rowIndex] = ramka.iloc[rowIndex, 3:31].sum()/maksPunkty
ramka["procent"] = procenty

ramka["ocena"] = pd.cut(ramka["procent"], np.array([0.0,0.5,0.6,0.7,0.8,0.9,1.0]), labels = ["2.0", "3.0", "3.5", "4.0", "4.5", "5.0"])
ramka